# ------------------------------------------------------------------
# File generated by save_this_cell
# Notebook: RepoMan_pyprover9.ipynb
# Saved: 2026-09-07 07:43:36
# ------------------------------------------------------------------


HTML_HEAD = """
<head>
<style>
table, th, td { border: 2px solid black;
                border-collapse: separate;}
</style>
</head>
<body>
"""

HTML_SET_LINK = """
<a href="problem_index.html" style="text-decoration:none">
<tt>Problem Set: __PROBLEM_SET__</tt></a>
"""

HTML_TOP = """
<h1> __TITLE__ </h1>
__ATTRIBUTION__

<p>
Your problem is to use <i>__LOGIC__</i> to represent the
following example of reasoning, and use
the <i>Prover9</i> theorem prover to prove that the
reasoning is valid.
</p>
"""

HTML_SUBMISSION_INSTRUCTIONS = """
<p>
Use the following template file to create your
Prover9 encoding of the problem:
<font size="+1">
<a href="__P9FILE__"><b><tt>__P9FILE__</tt></b></a>
</font>
</p>
"""

HTML_MARKS_EXPLANATION = """
<p>
<b>Marks: </b>There are two marks for each sentence,
making a total of <b>__MARKS__</b> marks.
</p>
"""

HTML_PROB_SPEC = """
<p>
__OUTLINE__

<h2>Problem Statement</h2>

__PROBLEM__
</p>
"""

HTML_VOCAB_SPEC = """
<h3>Non-Logical Vocabulary</h3>

__VOCABULARY__
"""

HTML_END_BODY = "</BODY>"

## This gives the full template that was used for the page used
## with the Gradescope implementation
HTML_TEMPLATE = ( HTML_HEAD + HTML_SET_LINK + HTML_SUBMISSION_INSTRUCTIONS +
                  HTML_MARKS_EXPLANATION + HTML_PROB_SPEC + HTML_VOCAB_SPEC +
                  HTML_END_BODY)


## This is the original html creation function for use with the gradescope
## implementation.
def make_html_for_problem(prob, problem_set="not in a set", filename=None):

    if filename == None:
        filename = prob["title"].title().replace(' ','') + ".p9"

    html = HTML_TEMPLATE
    html = html.replace("__TITLE__", prob["title"])
    html = html.replace( "__PROBLEM_SET__", problem_set )
    html = html.replace( "__ATTRIBUTION__", prob["attribution"])

    if "outline" in prob.keys():
      html = html.replace( "__OUTLINE__","<p><b>Outline: </b>" + prob["outline"])
    else:
      html = html.replace( "__OUTLINE__", "")

    html = html.replace( "__LOGIC__", prob["logic"] )
    html = html.replace( "__P9FILE__", filename )
    html = html.replace( "__MARKS__", str(len(prob["English"])*2) )
    problem = "<table cellpadding=6>"
    for i, ass in enumerate(prob["English"][:-1]):
        problem += "<tr bgcolor=#DDFFDD><td align=right><b>A{}</b></td> <td>{}</td></tr>\n".format(i+1,ass)
    problem += "<tr bgcolor=#DDFFFF><td align=right><b>Goal</b></td> <td>{}</td></tr>\n".format(prob["English"][-1])
    problem += "</table>"

    html = html.replace( "__PROBLEM__", problem )
    vocspec = ""
    for voctype in prob["vocabulary"]:
        voclist = prob["vocabulary"][voctype]
        tt_voclist = ["<font size=\"+1\"><tt>"+v+"</tt></font>" for v in voclist]
        vocstr = ", ".join(tt_voclist)
        vocspec += "<b>{}:</b> {}<p>".format(voctype, vocstr)

    html = html.replace( "__VOCABULARY__", vocspec )

    if "notes" in prob:
        html += "<h4>Notes:</h4>\n<ul>\n"
        for n in prob["notes"]:
            html += "<li>" + n + "</li>\n"
        html += "</ul>"

    html += HTML_END_BODY
    return html

if __package__:
  from .problems.propositional import PROBLEMS as PROPOSITIONAL_PROBLEMS
  from .problems.first_order_intro import PROBLEMS as FIRST_ORDER_INTRO_PROBLEMS
  from .problems.challenging import PROBLEMS as CHALLENGING_PROBLEMS
else:
  os.chdir(REPO_CODE)
  from problems.propositional import PROBLEMS as PROPOSITIONAL_PROBLEMS
  from problems.first_order_intro import PROBLEMS as FIRST_ORDER_INTRO_PROBLEMS
  from problems.challenging import PROBLEMS as CHALLENGING_PROBLEMS

PROBLEM_SETS = {
    "propositional": PROPOSITIONAL_PROBLEMS,
    "first_order_intro": FIRST_ORDER_INTRO_PROBLEMS,
    "challenging": CHALLENGING_PROBLEMS,
}

def get_problem(problem_set, problem_name):
    if problem_set not in PROBLEM_SETS:
        raise ValueError(f"Unrecognised problem set: {problem_set}")
    problems = PROBLEM_SETS[problem_set]
    if problem_name not in problems:
        raise ValueError(
            f"Problem {problem_name} not found in problem set {problem_set}")
    return problems[problem_name]

def problem_html( problem ):
    html = HTML_HEAD + HTML_TOP
    html = html.replace("__TITLE__", problem["title"])
    #html = html.replace( "__PROBLEM_SET__", problem_set )
    html = html.replace( "__PROBLEM_SET__", "" )
    html = html.replace( "__ATTRIBUTION__", problem["attribution"])
    html = html.replace( "__LOGIC__", problem["logic"] )

    if "outline" in problem.keys():
      html = html.replace( "__OUTLINE__","<p><b>Outline: </b>" + problem["outline"])
    else:
      html = html.replace( "__OUTLINE__", "")

    html +=  "\n<table cellpadding=6>"
    for i, ass in enumerate(problem["English"][:-1]):
        html += f"<tr bgcolor=#DDFFDD><td align=right><b>A{i+1}</b></td> <td>{ass}</td></tr>\n"
    goal = problem["English"][-1]
    html += f"<tr bgcolor=#DDFFFF><td align=right><b>Goal</b></td> <td>{goal}</td></tr>\n"
    html += "</table>"
    html += HTML_END_BODY
    return html

def display_problem_html(problem_set, problem_name):
    from IPython.display import HTML, display
    html = problem_html(get_problem(problem_set, problem_name))
    display(HTML(html))

#print("pyprover9.py version: electro-kebab")
